name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal:
          - "latest"
        ghc:
          - "9.4.4"

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      # src: https://harry.garrood.me/blog/easy-incremental-haskell-ci-builds-with-ghc-9.4/
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
          key: deps-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            dist-newstyle
          key: dist-${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Test native build
        run: cabal build

      - name: Run simple tests
        run: cabal test
